src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>TerritorySelfLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Territory Self-Relationship Lookup</description>
        <label>TerritorySelfLookup</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TerrUser__c.object
<CustomObject>
    <fields>
        <fullName>TerritoryToUserJunction__c</fullName>
        <description>Territory to User Junction Relationship</description>
        <label>TerritoryToUserJunction</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>TerrUsers</relationshipLabel>
        <relationshipName>TerrUsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserToTerritoryLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User to Territory Lookup Relationship</description>
        <label>UserToTerritoryLookup</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TerrUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TerrUser</label>
    <nameField>
        <label>TerrUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerrUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TerrUserService.cls
/*
 * Created by Pepperoner on 04.04.2019.
 */

public with sharing class TerrUserService {

    public static Set<Id> getTerritoriesId(List<TerrUser__c> terrUsers) {
        Set<Id> currentTerritoryIds = new Set<Id>();
        Set<Id> childTerritoryIds = new Set<Id>();

        for (TerrUser__c terrUser : terrUsers){
            currentTerritoryIds.add(terrUser.TerritoryToUserJunction__c);
        }

        List<Territory__c> firsTerritories = [
                SELECT Id,
                        TerritorySelfLookup__c
                FROM Territory__c
                WHERE Id IN :currentTerritoryIds
                OR TerritorySelfLookup__c IN :currentTerritoryIds
                OR TerritorySelfLookup__r.TerritorySelfLookup__c IN :currentTerritoryIds
        ];
        for (Territory__c territory : firsTerritories){
            if (territory.Id!=null) {
                childTerritoryIds.add(territory.Id);
            } else {
                return currentTerritoryIds;
            }
        }
        return childTerritoryIds;
    }

    public static Set<Id> getUsersId(List<TerrUser__c> terrUsers){
        Set<Id> userIds = new Set<Id>();
        for (TerrUser__c terrUser : terrUsers){
            userIds.add(terrUser.UserToTerritoryLookup__c);
        }
        return userIds;
    }
}